name: "CI/CD Pipeline - Users Service"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOTNET_VERSION: "9.0.x"  # Adjust version as needed
  APP_NAME: "ecommerce-users"
  DOCKER_IMAGE: "ecom-users-api"
  DOCKER_TAG: "latest"
  CONTAINER_NAME: "ecom-users-api-container"
  API_PORT: 5502

jobs:
  # ==========================================
  # BUILD & TEST JOB
  # ==========================================
  build-and-test:
    name: "Build & Test"
    runs-on: self-hosted

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Cache NuGet packages"
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: "Restore Dependencies"
        run: dotnet restore

      - name: "Build Solution"
        run: dotnet build --configuration Release --no-restore

      - name: "Run Unit Tests"
        run: |
          dotnet test --configuration Release --no-build --verbosity normal

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
      
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: "Build and push Docker image"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Ecom.Users.API/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ==========================================
  # DEPLOY JOB
  # ==========================================
  deploy:
    name: "Deploy to Environment"
    runs-on: self-hosted
    needs: build-and-test

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Ensure logs directory exists"
        run: mkdir -p ./logs

      - name: "Stop and Remove Existing Container"
        run: |
          # Check if container exists and stop it
          if docker ps -a --format '{{.Names}}' | grep -q "${{ env.CONTAINER_NAME }}"; then
            echo "Stopping existing container..."
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm ${{ env.CONTAINER_NAME }}
          else
            echo "No existing container found."
          fi

      - name: "Deploy with Docker"
        run: |
          echo "Starting container deployment..."
          
          # Pull the latest image
          docker pull ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}
          
          # Run container with proper configuration
          docker run -d \
            --name ${{ env.CONTAINER_NAME }} \
            --restart unless-stopped \
            -p ${{ env.API_PORT }}:80 \
            -e ASPNETCORE_ENVIRONMENT=Development \
            -v "$(pwd)/logs:/app/logs" \
            --network bridge \
            ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }}

          # Display container info
          echo "Container started with ID: $(docker ps -q -f name=${{ env.CONTAINER_NAME }})"

      - name: "Health Check"
        run: |
          # Wait for API to be healthy
          echo "Checking API health..."
          ATTEMPTS=0
          MAX_ATTEMPTS=12
          
          until curl -s -f http://localhost:${{ env.API_PORT }}/health || curl -s -f http://localhost:${{ env.API_PORT }}/healthz || [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; do
            echo "Waiting for API... Attempt $(($ATTEMPTS+1))/$MAX_ATTEMPTS"
            sleep 5
            ATTEMPTS=$(($ATTEMPTS+1))
          done
          
          if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
            echo "API health check failed after $MAX_ATTEMPTS attempts"
            docker logs ${{ env.CONTAINER_NAME }}
            exit 1
          else
            echo "API is healthy!"
          fi

      - name: "Show Container Status"
        run: |
          echo "🚀 Deployment completed!"
          echo ""
          echo "Docker Container Status:"
          docker ps --filter "name=${{ env.CONTAINER_NAME }}"
          echo ""
          echo "Container Logs:"
          docker logs --tail 20 ${{ env.CONTAINER_NAME }}
          echo ""
          echo "Service URL: http://localhost:${{ env.API_PORT }}"
          echo "Swagger UI: http://localhost:${{ env.API_PORT }}/swagger"

  # ==========================================
  # CLEANUP JOB (optional - uncomment if needed)
  # ==========================================
  # cleanup:
  #   name: "Cleanup"
  #   runs-on: self-hosted
  #   needs: deploy
  #   if: always()
  # 
  #   steps:
  #     - name: "Archive Logs"
  #       run: |
  #         # Create logs archive directory
  #         mkdir -p ./logs/archive/$(date +%Y%m%d)
  #
  #         # Copy current logs
  #         cp -r ./logs/* ./logs/archive/$(date +%Y%m%d)/ 2>/dev/null || true
  #
  #     - name: "Cleanup Docker Images"
  #       run: |
  #         # Remove dangling images
  #         docker image prune -f
